<?php
/**
 * @version 26/11/2018 10:23:51
 * @author jose_helio@gmail.com
 *
 */

include_once PATH_INCLUDE.'modal.phtml';
$data = HelperView::getViewData();
?>

<h2>Lista de Compras</h2>
<?php echo HelperView::printAlert()?>

<div id="commands">
	<?php echo $data['link']['add']?>
	<?php echo $data['link']['hst']?>
	<?php include_once PATH_INCLUDE.'busca.phtml';?>
</div>

<p>Total Estimado: <b><?php echo HelperData::printLikeMoney($data['total'])?></b></p>

<div id="table">
<?php if(key_exists('lista', $data)):?>
	<table>
    	<tr>
            <th></th>
            <th></th>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Preço Unit.</th>
            <th>Preço Total</th>
            <th></th>
      	</tr>
      	<?php foreach ($data['lista'] as $l):?>
        <tr class="to_hide">
            <td><?php echo $data['link']['check'][$l['id']]?></td>
            <td><?php echo $data['link']['udt'][$l['id']]?></td>          
            <td class="hidding"><?php echo $l['nome']?></td>
            <td><?php echo $l['quantidade']?></td>
            <td><?php echo HelperData::printLikeMoney($l['preco'])?></td>
            <td><?php echo HelperData::printLikeMoney($l['preco']*$l['quantidade'])?></td>    
            <td><?php echo $data['link']['del'][$l['id']]?></td>  
        </tr>
        <?php endforeach?>
    </table>
<?php endif?>
</div>

<h2>Comprados</h2>
<div id="table">
	<table id="comprados"></table>
</div>
