<?php
/**
 * @version 10/05/2019 13:47:41
 * @author jose_helio@gmail.com
 *
 */

include_once PATH_INCLUDE.'modal.phtml';
$data = HelperView::getViewData();
?>
<h2>Historico de Compras</h2>
<?php echo HelperView::printAlert()?>

<div id="commands">
	<?php include_once PATH_INCLUDE.'busca.phtml';?>
</div>

<div id="table">
<?php if(key_exists('lista', $data)):?>
	<table>
    	<tr>
            <th>Produto</th>
            <th>Última Quantidade</th>
            <th>Último Preço</th>
            <th>Última Compra</th>
      	</tr>
      	<?php foreach ($data['lista'] as $l):?>
        <tr>
            <td class="multi-content" width="50%">
                <div class="actions">
                    <?php echo $data['link']['check'][$l['id']]?>
                    <?php echo $data['link']['view'][$l['id']]?>
                </div>
                <div class="contents">
                    <?php echo $l['nome']?>
                </div>
            </td>   
            <td width="10%"><?php echo $l['lastQtd']?></td>
            <td width="20%"><?php echo HelperData::printLikeMoney($l['lastPreco'])?></td>
            <td width="20%"><?php echo date('d/m/Y', strtotime($l['lastDate']))?></td>
        </tr>
        <?php endforeach?>
    </table>
<?php endif;?>
</div>
