<?php
/**
 * @version 17/08/2020 16:53:22
 * @author jose_helio@gmail.com
 *
 */

$data = HelperView::getViewData();
//var_dump($data['lista']);die;
?>

<h2>Comprar</h2>
<?php echo HelperView::printAlert()?>

<nav id="commands">
	<?php echo $data['link']['add']?>
	<?php echo $data['link']['hst']?>
	<?php include_once PATH_INCLUDE.'busca.phtml';?>
</nav>

<p>Total Estimado: <b><?php echo HelperData::printLikeMoney($data['total'])?></b></p>

<div id="table">
<?php if(key_exists('lista', $data)):?>
	<table>
    	<tr>
            <th>Produto</th>
            <th>Quant</th>
            <th>Preço Unit.</th>
            <th>Preço Total</th>
      	</tr>
      	<?php foreach ($data['lista'] as $l):?>
        <tr class="to_hide">      
            <td class="hidding" width="50%">
            	<b><?php echo $l['produto_nome']?></b>
				<?php echo substr($l['nome'], strlen($l['produto_nome'])+1)?>
            </td>
            <td width="10%"><?php echo $l['quantidade']?></td>
            <td width="20%"><?php echo HelperData::printLikeMoney($l['preco'])?></td>
            <td width="20%"><?php echo HelperData::printLikeMoney($l['preco']*$l['quantidade'])?></td>  
        </tr>
        <?php endforeach?>
    </table>
<?php endif?>
</div>

<div id="comprados">
    <h2>No Carrinho</h2>
    <div id="table">
    	<table>
        	<tr>
                <th>Produto</th>
                <th>Quant</th>
                <th>Preço Unit.</th>
                <th>Preço Total</th>
          	</tr>
      	</table>
    </div>
</div>