<?php
/**
 * @version 02/05/2019 13:45:25
 * @author jose_helio@gmail.com
 *
 */include_once PATH_INCLUDE.'modal.phtml';
$data = HelperView::getViewData();
?>

<h2>Importar Compras</h2>
<?php echo HelperView::printAlert()?>

<ul>
	<?php foreach($data['lista'] as $filename):?>
		<li><a href="<?php echo URI."csv/read/file/{$filename}"?>"><?php echo date('d/m/Y', strtotime($filename))?></a></li>
	<?php endforeach?>
</ul>