<?php
/**
 * @version 08/05/2019 15:45:25
 * @author jose_helio@gmail.com
 *
 */include_once PATH_INCLUDE.'modal.phtml';
$data = HelperView::getViewData();
?>

<h2>Registrar Compras</h2>
<?php echo HelperView::printAlert()?>

<details>
	<summary>Embalagem - Unidade</summary>
	<table>
		<tr>
			<th colspan="2">Banco de Dados</th>
			<th colspan="2">No Arquivo</th>
		</tr>
		<tr>
			<th>id</th>
			<th>nome</th>
			<th>id</th>
			<th>nome</th>
		</tr>
	</table>
</details>

<details>
	<summary>Embalagem - Tipo</summary>
	<table>
		<tr>
			<th colspan="2">Banco de Dados</th>
			<th colspan="2">No Arquivo</th>
		</tr>
		<tr>
			<th>id</th>
			<th>nome</th>
			<th>id</th>
			<th>nome</th>
		</tr>
	</table>
</details>

<details>
	<summary>Produto</summary>
	<table>
		<tr>
			<th colspan="2">Banco de Dados</th>
			<th colspan="2">No Arquivo</th>
		</tr>
		<tr>
			<th>id</th>
			<th>nome</th>
			<th>id</th>
			<th>nome</th>
		</tr>
	</table>
</details>