<?php
/**
 * @version 08/05/2019 15:45:25
 * @author jose_helio@gmail.com
 *
 */include_once PATH_INCLUDE.'modal.phtml';
$data = HelperView::getViewData();
?>

<h2>Registrar Compras</h2>
<?php echo HelperView::printAlert()?>

<?php foreach($data['lvl1'] as $table=>$read):?>
<details>
	<summary><?php echo $table?></summary>
	<table>
		<tr>
			<th>id</th>
			<th>nome</th>
		</tr>
		<?php foreach ($read as $line):?>
			<tr>
				<td><?php echo $line['id']?></td>
				<td><?php echo $line['nome']?></td>
			</tr>
		<?php endforeach?>
	</table>
</details>
<?php endforeach?>