<?php
/**
 * @version 02/05/2019 13:32:08
 * @author jose_helio@gmail.com
 *
 */

include_once PATH_INCLUDE.'modal.phtml';
$data = HelperView::getViewData();
?>
<h2>Mercadorias</h2>
<?php echo HelperView::printAlert()?>

<div id="commands">
	<?php echo $data['link']['add']?>
	<?php include_once PATH_INCLUDE.'busca.phtml';?>
</div>

<div id="table">
<?php if(key_exists('lista', $data)):?>
	<table>
    	<tr>
            <th width="50%">Produto</th>
            <th>Tipo</th>
      	</tr>
      	<?php foreach ($data['lista'] as $l):?>
        <tr>
            <td class="multi-content">
                <div class="actions">
                    <?php echo $data['link']['add_list'][$l['id']]?>
                    <?php echo $data['link']['udt'][$l['id']]?>
                    <?php echo $data['link']['del'][$l['id']]?>
                </div>
                <div class="contents">
                    <?php echo $l['nome']?>
                </div>                
            </td>   
            <td><?php echo $l['tipo_nome']?></td>
        </tr>
        <?php endforeach?>
    </table>
<?php endif;?>
</div>